name: Basura
on:
  push:
    branches: [ main ]
    paths: 
      - 'bot/basura/**'
      - 'extension/about/**'
      - 'extension/anilist/**'
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Java JDK
        uses: actions/setup-java@v3
        with:
          distribution: adopt
          java-version: 11
      - name: Setup Gradle Dependencies Cache
        uses: actions/cache@v2
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-caches-${{ hashFiles('**/*.gradle', '**/*.gradle.kts') }}
      - name: Setup Gradle Wrapper Cache
        uses: actions/cache@v2
        with:
          path: ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-wrapper-${{ hashFiles('**/gradle/wrapper/gradle-wrapper.properties') }}
      - name: Build Distribution
        run: ./gradlew bot:basura:installDist
      - name: Upload Distribution
        uses: actions/upload-artifact@v3
        with:
          name: basura
          path: ./bot/basura/build/install/basura
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download Distribution
        uses: actions/download-artifact@v3
        with:
          name: basura
          path: ./basura
      - name: Deploy to Host
        uses: yeshan333/rsync-deploy-action@v1.0.0
        with:
          source_path: .
          destination_path: /bot
          remote_server_ip: ${{secrets.HOST}}
          ssh_port: ${{secrets.PORT}}
          ssh_login_username: ${{secrets.USER}}
          ssh_private_key: ${{secrets.KEY}}
          rsync_args: -o -g
      - name: Restart Discord Bot
        uses: garygrossgarten/github-action-ssh@v0.6.3
        with:
          command: systemctl restart basura
          host: ${{secrets.HOST}}
          username: ${{secrets.USER}}
          port: ${{secrets.PORT}}
          privateKey: ${{secrets.KEY}}
